name: PBT e-Reporting System CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.Ahmadmohdali }}" | docker login -u "${{ secrets.hamizan.al@s.unikl.edu.my }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t mizn08/my-html-app .
        docker push mizn08/my-html-app:latest
