name: PBT e-Reporting System CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Verify Docker Installation
      run: docker --version

    # Log in to Docker Hub securely
    - name: Log in to Docker Hub
      run: echo "${{ secrets.mizn08 }}" | docker login -u "${{ secrets.Ahmadmohdali }}" --password-stdin
      shell: bash

    # Build and push Docker image
    - name: Build and Push Docker Image
      run: |
        docker build -t my-html-app .
        docker tag my-html-app hamizan.ali/my-html-app:latest
        docker push hamizan.ali/my-html-app:latest
      shell: pwsh
